version: '3'
services:
  udagram-user:
    image: hmisonne/udagram-user
    build:
      context: ./udagram-api/udagram-api-user
  udagram-feed:
    image: hmisonne/udagram-feed
    build:
      context: ./udagram-api/udagram-api-feed