version: '3'
services:
  udagram-user:
    build:
      context: ./udagram-api/udagram-api-user
    image: hmisonne/udagram-user
  udagram-feed:
    build:
      context: ./udagram-api/udagram-api-feed
    image: hmisonne/udagram-feed