version: "3"
services:
  reverseproxy:
      image: hmisonne/udagram-reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - udagram-user
        - udagram-feed     
  udagram-user:
    image: hmisonne/udagram-user
  udagram-feed:
    image: hmisonne/udagram-feed
    volumes:
      - $HOME/.aws:/root/.aws
  udagram-frontend:
    image: hmisonne/udagram-frontend
    ports:
      - "8100:80"
