version: '3'
services:
  udagram-user:
    build:
      context: ../../udagram-api-user
      dockerfile: Dockerfile
    image: hmisonne/udagram-user
  udagram-feed:
    build:
      context: ../../udagram-api-feed
      dockerfile: Dockerfile
    image: hmisonne/udagram-feed
  reverseproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: hmisonne/reverseproxy
  frontend:
    build:
      context: ../../udagram-frontend  
    image: hmisonne/udagram-frontend