apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram
  labels:
    app: udagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
      - name: udagram-frontend
        image: hmisonne/udagram-frontend
        ports:
        - containerPort: 80